config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admin_users
  get 'top/index'

  resources :comments
  root to: "top#index"
  resources :photos

  devise_for :users, :controllers => {
    :omniauth_callbacks => 'users/omniauth_callbacks',
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
	 mount_uploader :image, ImageUploader
	 belongs_to :user
	 has_many :comments

	 is_impressionable
	 
	acts_as_taggable_on :labels # post.label_list が追加される
  	acts_as_taggable            # acts_as_taggable_on :tags のエイリアス
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :login_check, only: [:new, :edit, :update, :destroy]
  before_action :set_current_user_photo, only: [:edit, :update, :destroy]


  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
    @photos = Photo.order("Created_at DESC")

  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.includes(:user).find(params[:id])
    @comments = @photo.comments.includes(:user).all
    @comment  = @photo.comments.build(user_id: current_user.id) if current_user

    impressionist(@photo, nil, :unique => [:session_hash])
    @page_views = @photo.impressionist_count

  end

  # GET /photos/new
  def new
     @photo = current_user.photos.build
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: '画像の投稿が完了しました。' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: '画像の編集が完了しました。' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: '画像の消去が完了しました。' }
      format.json { head :no_content }
    end
  end

  private
    def login_check
      unless user_signed_in?
        flash[:alert] = "ログインしてください"
        redirect_to root_path
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_current_user_photo
      @photo = current_user.photos.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
       params.require(:photo).permit(:image, :caption, :description, :user_id)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
        <div id="logbox">
          <form id="signup" method="post" action="/signup">
            <div class="field" style="padding-top:10px;">
              <%= f.file_field :image, :class => "input pass" %>
            </div>
            <div class="field">
              <%= f.text_area :caption, :class => "input pass", :placeholder => "作品名を入力してください", :maxlength => "30" %>
              <%= f.text_area :description, :class => "input pass",:placeholder => "作品の説明を入力してください", :size => "20x10" %>
              <%= f.hidden_field :user_id, :class => "input pass" %>
            </div>
            <div class="actions">
              <%= f.submit "画像を投稿する", :class => "inputButton" %>
            </div>
          </form>
        </div>
      </div>
    </div>



<% end %>

app/views/photos/edit.html.erb
<h1>写真を編集する</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

  <div class="row">
    <% @photos.each do |photo| %>
      <div class="col-md-4 col-xs-6">
      <%= link_to photo, class: "photo_class" do %>
        <article class="g_area">
          <div class="img_area">
            <%= image_tag photo.image_url(:thumb) %>
          </div>
          <div class="text_area">
            <div class="top clearfix">
              <div class="title">
                <%= photo.caption %>
              </div>
            </div>
             <p><%= number_with_delimiter(@page_views) %></p>
            <div class="bottom clearfix">
              <div class="name">
                <% if user_signed_in? %>
                  <%= image_tag current_user.avatar_url %>
                  <%= photo.user.username %>
                <% end %>
              </div>
              <div class="link">
              
              </div>
            </div>
          </div>
        </article>
      <% end %>
      </div><!--/.col-md-3 col-xs-6-->
    <% end %>
  </div><!--/.row-->

app/views/photos/new.html.erb
<h1>作品を投稿する</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

    <div class="card">
      <div class="container-fliud">
        <div class="wrapper row">
          <div class="preview col-md-6">
            
            <div class="preview-pic tab-content">
              <div class="tab-pane active" id="pic-1"><%= image_tag(@photo.image_url) if @photo.image.present? %></div>
              <div class="tab-pane" id="pic-2"><%= image_tag(@photo.image_url) if @photo.image.present? %></div>
              <div class="tab-pane" id="pic-3"><%= image_tag(@photo.image_url) if @photo.image.present? %></div>
              <div class="tab-pane" id="pic-4"><%= image_tag(@photo.image_url) if @photo.image.present? %></div>
              <div class="tab-pane" id="pic-5"><%= image_tag(@photo.image_url) if @photo.image.present? %></div>
            </div>
            <ul class="preview-thumbnail nav nav-tabs">
              <li class="active"><a data-target="#pic-1" data-toggle="tab"><%= image_tag(@photo.image_url) if @photo.image.present? %></a></li>
              <li><a data-target="#pic-2" data-toggle="tab"><%= image_tag(@photo.image_url) if @photo.image.present? %></a></li>
              <li><a data-target="#pic-3" data-toggle="tab"><%= image_tag(@photo.image_url) if @photo.image.present? %></a></li>
              <li><a data-target="#pic-4" data-toggle="tab"><%= image_tag(@photo.image_url) if @photo.image.present? %></a></li>
              <li><a data-target="#pic-5" data-toggle="tab"><%= image_tag(@photo.image_url) if @photo.image.present? %></a></li>
            </ul>
            
          </div>
          <div class="details col-md-6">
            <h3 class="product-title"><%= @photo.caption %></h3>
            <div class="rating">
              <div class="stars">
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
              </div>
              <span class="review-no"><%= number_with_delimiter(@page_views) %> reviews</span>
            </div>
            <p class="product-description">
              <%= @photo.description %>
              
            </p>
            <h4 class="price">current price: <span>$180</span></h4>
            <p class="vote"><strong>91%</strong> of buyers enjoyed this product! <strong>(87 votes)</strong></p>
            <h5 class="colors">タグ：
              <span>自由制作</span>
              <span>三年プロダクト</span>
              <span>三年スペース</span>
            </h5>
            <div class="action">
              <button class="like btn btn-default" type="button"><span class="fa fa-heart"></span></button>
              <% if user_signed_in? && @photo.user == current_user %>
                <%= link_to 'Edit', edit_photo_path(@photo), :class =>"like btn btn-default" %>
                <%= link_to 'Destroy', @photo, method: :delete, data: { confirm: '本当に消去しますか？' }, :class =>"like btn btn-default" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>


  <!-- コメント表示 -->
  <div class="row">
    <div class="col-md-8">
      <h2 class="page-header">コメント</h2>
      <section class="comment-list">
        <!-- First Comment -->
        <% @comments.each do |comment| %>
          <article class="row">
            <div class="col-md-2 col-sm-2 hidden-xs">
              <figure class="thumbnail">
                <img class="img-responsive" src="http://www.keita-gaming.com/assets/profile/default-avatar-c5d8ec086224cb6fc4e395f4ba3018c2.jpg" />
                <figcaption class="text-center"><%= comment.user.username %></figcaption>
              </figure>
            </div>
            <div class="col-md-10 col-sm-10">
              <div class="panel panel-default arrow left">
                <div class="panel-body">
                  <header class="text-left">
                    <div class="comment-user"><i class="fa fa-user"></i> <%= comment.user.username %></div>
                    <time class="comment-date"><i class="fa fa-clock-o"></i> Dec 16, 2014</time>
                  </header>
                  <div class="comment-post">
                    <p>
                      <%= comment.body %>
                    </p>
                  </div>
                  <!-- <p class="text-right"><a href="#" class="btn btn-default btn-sm"><i class="fa fa-reply"></i> 返信する</a></p> -->
                  <p class="text-right"><%= link_to 'Delete', comment_path(comment), method: :delete %></p>
                  <%= link_to 'Edit', edit_comment_path(comment) %>
                  <%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
                </div>
              </div>
            </div>
          </article>
        <% end %>
      </section>
    </div>
  </div>


  <!-- コメント入力欄 -->
  <div class="row">
<!--     <% @comments.each do |comment| %>
      <div>
        <strong><%= comment.user.user_name %></strong>
        <br />
        <p><%= comment.body %></p>
        <%= comment.user.username %>
        <% if user_signed_in? && comment.user == current_user %>
          <p><%= link_to 'Delete', comment_path(comment), method: :delete %></p>
        <% end %>
      </div>
    <% end %> -->

    <div class="col-lg-12">
     <div class="well well-lg">
        <div class="media-body">                                                
          <div class="form-group" style="padding:12px;">
            <%= render 'comments/form' %>
          </div>             
        </div>
      </div>
    </div> 
  </div>