config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admin_users
  get 'top/index'

  resources :comments
  root to: "top#index"
  resources :photos

  devise_for :users, :controllers => {
    :omniauth_callbacks => 'users/omniauth_callbacks',
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>ikenk</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <header id="top-head">
    <div class="inner">
        <div id="mobile-head">
          <a href="/" class="logo smooth"><%= embedded_svg("ikenk.svg", class: "logo") %></a>
          <% if user_signed_in? %>
            <%= image_tag current_user.avatar_url %>
          <% end %>
          <div id="nav-toggle">
            <div>
              <span></span>
              <span></span>
              <span></span>
            </div>
          </div>
        </div>
      <nav id="global-nav">
        <ul>
          <li><%= link_to 'ギャラリー', photos_path, :class => 'link smooth' %></li>
          <span <% if user_signed_in? %> class="hidden"  <% end %> >
            <li><%= link_to "ログイン", new_user_session_path, :class => 'link smooth'  %></li>
            <li><%= link_to "新規作成", new_user_registration_path, :class => 'link smooth'  %> </li>
          </span>
          <% if user_signed_in? %>
            <li><%= link_to '画像を投稿する', new_photo_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.username %><span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
                <li class="divider"></li>
                <li><%= link_to "logout", destroy_user_session_path, method: :delete, :class => 'link smooth'  %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>

  <div class="container" style="padding-top:70px;">
    <%= yield %>
  </div>

  <footer>
    <div class="container">
      <div class="clearfix">
        <div class="col-xs-12">
          <p><small>Copyright &copy; ikenk All Rights Reserved.</small></p>
        </div>
      </div>
    </div>
  </footer>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</body>
</html>